"""add game and move tables for tic-tac-toe

Revision ID: ba52a6fe9545
Revises: 3b2e190b1663
Create Date: 2025-11-08 23:39:05.577424

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'ba52a6fe9545'
down_revision = '3b2e190b1663'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game',
    sa.Column('opponent_type', sa.Enum('AI', 'ALGORITHM', name='opponenttype'), nullable=False),
    sa.Column('difficulty', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('board', sqlmodel.sql.sqltypes.AutoString(length=9), nullable=False),
    sa.Column('status', sa.Enum('IN_PROGRESS', 'FINISHED', 'DRAW', name='gamestatus'), nullable=False),
    sa.Column('current_player', sa.Enum('X', 'O', name='player'), nullable=False),
    sa.Column('winner', sa.Enum('X', 'O', name='player'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_user_id'), 'game', ['user_id'], unique=False)
    op.create_table('move',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('player', sa.Enum('X', 'O', name='player'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_move_game_id'), 'move', ['game_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_move_game_id'), table_name='move')
    op.drop_table('move')
    op.drop_index(op.f('ix_game_user_id'), table_name='game')
    op.drop_table('game')
    # ### end Alembic commands ###
